### ISSUE TITLE
Consider writing out long-form options and using dash-case

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/canonical-data-syncer#76] opened 2020-10-23 17:29 UTC
I'm trying to use it, and constantly keep  making mistakes because what it should be isn't matching my intuition. This is completely anecdotal. There might be many many clis that use the format used here.

1. Prefer `--dash-case` over `--camelCase`,
1. Prefer `--problem-specifications-dir` or `--problem-specifications-directory` over `--prob-spec-dir`

Almost every single cli I've worked with uses `dash-case`, some older ones use `snake_case`.

![image](https://user-images.githubusercontent.com/1964376/97034968-f61e6780-1565-11eb-9298-06fac1a05d1c.png)

**Comment by ee7** [comment] 2020-10-23 17:43
> 1. Prefer `--dash-case` over `--camelCase`,

Sure, can think about that. I was intending to eventually make it style-insensitive anyway. So any of these should be valid:

```
--probSpecsDir
--probspecsdir
--prob-specs-dir
--prob_specs_dir
--PROBSPECSDIR
--prO_b----sPe____CsDIR
```

And also also that "any unambiguous long-option prefix should be allowed", for example:

```
--prob
```

> 2. Prefer `--problem-specifications-dir` or `--problem-specifications-directory` over `--prob-spec-dir`

Yeah, maybe that looks better, especially if it's `dash-case`.

The current style is partly just because it's written in Nim. And at least the `nim --help` has `--camelCase` :)

**Comment by ErikSchierboom** [comment] 2020-10-23 17:55
> Sure, can think about that. I was intending to eventually make it style-insensitive anyway

How very Nim-y of you! ;)

**Comment by ErikSchierboom** [comment] 2020-10-23 17:56
And I agree with the issue. Good idea.

**Comment by SleeplessByte** [comment] 2020-10-23 17:57
Love all of this @ee7

**Comment by ee7** [comment] 2020-10-26 11:07
I can fix all of the issues mentioned here, but it won't happen all in one PR.

So I've made separate issues to track everything, and I'll close this one as a duplicate(!). Sorry.

Duplicate of #80

**Closed by ee7** 2020-10-26 11:07 UTC
